### ISSUE TITLE
HA doesn't seem to store new values in history

### ISSUE THREAD

**Issue by doctorkb** [twrecked/hass-virtual#111]
This is a loose bug report, as I'm not sure where the issue is specifically.

I upgraded this integration at the same time as going to 2024.07.0. Since then, my virtual sensors seem to receive the values, but they aren't stored by Recorder. Other entities do get stored correctly, so Recorder isn't completely broken.

I'll add more as I observe, but figured it was worth getting this vague report started.

**Comment by doctorkb** [comment]
![image](https://github.com/twrecked/hass-virtual/assets/1383663/ee52f7f2-7610-4d80-afb4-c1f51fc938ea)

**Comment by doctorkb** [comment]
Probably related to https://community.home-assistant.io/t/psa-2024-7-recorder-problems/746428

**Comment by twrecked** [comment]
I'm still seeing the values appear here. And I don't use the recording filter that is mentioned in the bug report.

Is there anything in the logs showing a backtrace?

**Comment by doctorkb** [comment]
I'm wondering if it wasn't icloud3 interfering.  The odd thing was how it only seemed to be my virtual devices that weren't being recorded (and the icloud3 ones).  The ecobee integration was recording the data correctly.

**Comment by doctorkb** [comment]
Turns out applying the fix to icloud3 [here](https://github.com/gcobb321/icloud3/issues/349#issuecomment-2214055930) resolved the issue.  It's really odd to me that it was storing fine for ecobee but not hass-virtual.  I wonder if the "official" integrations are sandboxed from the HACS-installed ones?
