### ISSUE TITLE
will be removed in HA Core 2025.1.

### ISSUE THREAD

**Issue by jove01** [twrecked/hass-virtual#130]
I get this warning

`Logger: homeassistant.const
Quelle: helpers/deprecation.py:197
Erstmals aufgetreten: 11:04:24 (4 Vorkommnisse)
Zuletzt protokolliert: 11:04:24

FREQUENCY_GIGAHERTZ was used from virtual, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfFrequency.GIGAHERTZ instead, please report it to the author of the 'virtual' custom integration
POWER_VOLT_AMPERE was used from virtual, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfApparentPower.VOLT_AMPERE instead, please report it to the author of the 'virtual' custom integration
PRESSURE_HPA was used from virtual, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPressure.HPA instead, please report it to the author of the 'virtual' custom integration
VOLUME_CUBIC_METERS was used from virtual, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfVolume.CUBIC_METERS instead, please report it to the author of the 'virtual' custom integration`

**Comment by ildar170975** [comment]
similar: https://github.com/twrecked/hass-virtual/issues/132

**Comment by twrecked** [comment]
Fixed in 0.9
