### ISSUE TITLE
2024.9 warning: POWER_VOLT_AMPERE_REACTIVE

### ISSUE THREAD

**Issue by ildar170975** [twrecked/hass-virtual#132]
WARNING (ImportExecutor_0) [homeassistant.const] POWER_VOLT_AMPERE_REACTIVE was used from virtual, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'virtual' custom integration

**Comment by Tony763** [comment]
Doc: Full list of deprecated constants can by found there: https://github.com/home-assistant/core/blob/dev/homeassistant/const.py

Searching for "2025.1" reveal all of them.

**Comment by ildar170975** [comment]
Seems to be fixed in beta.17
