### ISSUE TITLE
Support For Garage Doors

### ISSUE THREAD

**Issue by ImaBadCoder** [twrecked/hass-virtual#15]
Would love to see support for Garage Doors. Would make the automation dev process so much easier.

**Comment by twrecked** [comment]
Do you have a link to the garage door component?

**Comment by ImaBadCoder** [comment]
Hmm. Not sure. I see that the Binary_sensor shows a garage_door device class from https://www.home-assistant.io/integrations/binary_sensor/.  I know that my garage door controller from GoControl has 2 more modes than the open close shown as outputs.

https://www.gocontrol.com/detail.php?productId=4

the 4 stages are:
opening
open
closing
closed

Let me know if you need more information.

**Comment by TheNoim** [comment]
https://developers.home-assistant.io/docs/core/entity/cover/
