### ISSUE TITLE
Virtual Switches

### ISSUE THREAD

**Issue by Steven-D-Morgan** [twrecked/hass-virtual#17]
I have been using these for awhile as a way to bypass automations. Having a virtual switch as a condition in the sequence. They have worked flawlessly up until recently. I am not sure when they started to be ignored in automations but they have started at some point in recent months. 

Wondering if a home assistant update changed the behavior of your code?

**Comment by twrecked** [comment]
I will take a look.

**Comment by Steven-D-Morgan** [comment]
Awesome thank you so much sir! Like seriously

**Comment by twrecked** [comment]
What version of home assistant are you on?

**Comment by Steven-D-Morgan** [comment]
Running a NUC

- Core 2021.9.7
- Supervisor 2021.09.0
- Home Assistant OS 6.4
