### ISSUE TITLE
homeassistant 0.110 - SwitchDevice is deprecated, modify VirtualSwitch to extend SwitchEntity

### ISSUE THREAD

**Issue by sanderlv** [twrecked/hass-virtual#2]
Log Details (WARNING)
Logger: homeassistant.components.switch
Source: components/switch/__init__.py:125
Integration: Switch (documentation, issues)
First occurred: 4:15:22 PM (1 occurrences)
Last logged: 4:15:22 PM

SwitchDevice is deprecated, modify VirtualSwitch to extend SwitchEntity

**Comment by twrecked** [comment]
Should be fixed with #3. In release 0.5.
