### ISSUE TITLE
A way to toggle the virtual switch state from Automation (a service maybe?)

### ISSUE THREAD

**Issue by xaviertidus** [twrecked/hass-virtual#20]
I will prefix with an admission that I may be doing the wrong thing :)

I use a virtual switch as a global "Do Not Disturb" state for various automation. Currently this switch is toggled in lovelace by way of a button.

If someone forgets to "untoggle" the DND then we could go for days missing doorbells etc. I am attempting to create automation to reset the virtual button state daily, however the virtual switch cannot be *physically* toggled by automation, and I lack a way to address this.

Perhaps a service for hass-virtual would allow this outcome? 

Thank you

**Comment by xaviertidus** [comment]
doh! service: switch.turn_off

I should sleep haha. thank you and apologies!

**Comment by twrecked** [comment]
No worries. Glad you got it working!
