### ISSUE TITLE
Referencing 'virtual' from separate yaml files

### ISSUE THREAD

**Issue by spry-salt** [twrecked/hass-virtual#26]
I like the 'virtual' integration, it's such a great idea and works really well, thanks for taking the time to share it with the community.

I recently separated the different elements of the HA configuration.yaml file into separate files (e.g. sensors, fans...). I couldn't figure out how to still reference 'virtual' sensors (for example) from a separate file, I could only do it from within configuration.yaml. 

Could you point me in the right direction please?

**Comment by jazzyisj** [comment]
I have my virtual components mixed in with my [packages ](https://www.home-assistant.io/docs/configuration/packages/)(for example I have a package for lights, and my virtual lights are set up within that package along with all my other light stuff).

https://www.home-assistant.io/docs/configuration/packages/

Have a look at [my config](https://github.com/jazzyisj/home-assistant-config) if you want - search for "virtual" in my code, you'll find where I set my stuff up.
