### ISSUE TITLE
Virtual Fans - Platform Error v2202.4

### ISSUE THREAD

**Issue by jazzyisj** [twrecked/hass-virtual#27]
`Platform error fan.virtual - cannot import name 'SPEED_HIGH' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)`

**Comment by tobyworks** [comment]
same.

**Comment by twrecked** [comment]
Same here. I'll take a look.

**Comment by jazzyisj** [comment]
Fixed in v0.7.0.6
