### ISSUE TITLE
Possible to add virtual Climate?

### ISSUE THREAD

**Issue by Johnnybyzhang** [twrecked/hass-virtual#31]
I'd love to implement your component in my home-assistant build, yet there is one missing piece.
Would it be possible for you to add virtual climate entity support?

**Comment by CamTosh** [comment]
@Johnnybyzhang you can use https://www.home-assistant.io/integrations/generic_thermostat/

**Comment by tetele** [comment]
The Generic Thermostat does not support `ClimateEntityFeature.TARGET_TEMPERATURE_RANGE`, unfortunately.
