### ISSUE TITLE
white_value will be removed from light in Home Assistant Core 2022.9

### ISSUE THREAD

**Issue by emontnemery** [twrecked/hass-virtual#33]
`white_value` will be removed from `light` in Home Assistant Core 2022.9, which will break this custom component if it's not updated.

Background here: https://github.com/home-assistant/core/pull/76926

**Comment by twrecked** [comment]
Thanks for the info. I'll fix it.

**Comment by twrecked** [comment]
It should be fixed in 0.7.7.
