### ISSUE TITLE
Virtual Sensor resets itself after certain time

### ISSUE THREAD

**Issue by czerwofm** [twrecked/hass-virtual#39]
sensor:
  - platform: virtual
    name: 'zawor_mieszajacy_zadana'
    class: temperature
    initial_value: 37
    initial_availability: true

In the devolper mode, I change the state from 37 to 45 and after a few seconds the value returns to 37. If the value is not set, the set value is completely erased and the sensor goes into unavailable state. 
What to do in this case?

**Comment by twrecked** [comment]
Sorry for the delay getting back, are you still seeing this?

If so, how are you changing the state? Are you using the virtual service or another method?

**Comment by twrecked** [comment]
Thinking about it:

How are you changing the device state? You might need to use one of the virtual service calls to make it work.

The documents aren't great but you can see the service calls mentioned at the bottom of [this](https://github.com/twrecked/hass-virtual#binary-sensors) section.
