### ISSUE TITLE
Virtual Compenents in Node Red

### ISSUE THREAD

**Issue by juzel69** [twrecked/hass-virtual#4]
Is it possible to use the virual components in node-red? I have tried to do so, but can not find the defined virtual elements in node-red.

**Comment by twrecked** [comment]
I have very little experience with Node Red but I don't see why you shouldn't be able to use the virtual components in it.

The virtual components themselves just look and act like their non-virtual counterparts except the only thing they change is their internal state. For example, if Node Red presents you with a list of switches, virtual switches should appear along side non-virtual switches.

**Comment by juzel69** [comment]
Thank you for your fast answer. I play a while with node-RED. After activating virtual Devices, I have to restart node-RED, then the virtual elements are available.

**Comment by twrecked** [comment]
Excellent. Glad it's working!
