### ISSUE TITLE
Virtual sensor does not trigger Alexa routine

### ISSUE THREAD

**Issue by tmorse305** [twrecked/hass-virtual#40]
I'm trying to use a binary sensor to trigger an Alexa routine.  The sensor appears in the device list on Alexa.  I can see the state change as I toggle it from HA.  The sensor appears as a choice when I create the routine, but the routine never triggers even though I can see the sensor toggle from the devices page in Alexa.  I have tried 'motion', 'window' and 'presence' classes but none work.  Is there a trick to getting the routine to function?

Thank you.

**Comment by twrecked** [comment]
How are you changing the device state? You might need to use one of the virtual service calls to make it work.

The documents aren't great but you can see the service calls mentioned at the bottom of [this](https://github.com/twrecked/hass-virtual#binary-sensors) section.

**Comment by neil1111** [comment]
This will exactly be my use case, but I tried to create a device but it won't appear. See other issue #56
