### ISSUE TITLE
Troubleshooting device tracker

### ISSUE THREAD

**Issue by GRClark** [twrecked/hass-virtual#51]
Trying to change state of device tracker and getting the following error.  Looking for any insight you can offer.  

This is what I used under services in developer tools.  

`service: device_tracker.see
data:
  dev_id: device_tracker.beacon_dad
  location_name: home
`

![704380AF-4A1A-477D-AFC9-632E0CEADA3A](https://user-images.githubusercontent.com/5118059/214726805-87de3891-21f5-4e3d-b118-9abfff78ff3b.png)

**Comment by twrecked** [comment]
You get this working? It should just be `beacon_dad`.

**Comment by GRClark** [comment]
Closed prematurely but thanks for reaching out.  Your advice did the trick, thanks again. On Jan 25, 2023, at 8:45 PM, Steve Herrell ***@***.***> wrote:﻿
You get this working? It should just be beacon_dad.
