### ISSUE TITLE
Possible to add virtual fan?

### ISSUE THREAD

**Issue by jazzyisj** [twrecked/hass-virtual#6]
Would it possible to add a virtual fan to this integration?

**Comment by twrecked** [comment]
I think so. I'll take a look.

**Comment by twrecked** [comment]
It's included with PR #8 and in version 0.7.

Let me know if it looks ok.

**Comment by jazzyisj** [comment]
Just tried it out - works great!  Thank you.  I have a basement reno in the works that's been stalled due to covid.  Your integration has enabled me to get the automations written and actually debugged for the lighting (and now fans) and front end done for it in the meantime.  I also use the lock to do the same while I decide which route I'm going with those.  It has worked perfectly. 

I did like how you didn't preface the entity_id with "virtual" for fans like the lights are.  With the fans I won't have to change the entity_id's in the config like I will when I do the lights once I install the switches.  No biggie, just slightly more convenient.

Thank you for taking the time to add the fan in.  I'll close the issue.

**Comment by twrecked** [comment]
Glad it works!

And I don't think the naming was me, looks like something to do with the Fan component forgetting to add the domain.
