### ISSUE TITLE
Lights are always Unavailable

### ISSUE THREAD

**Issue by DVEntertainment** [twrecked/hass-virtual#66]
Hi, 
I'm trying to control a light with multiple color-options. i read the virtual object with node-red and send the controls to the light via http requests. That all works except i can't have multiple color-wheels in 1 light entity. So i tried to create multiple light entities, but they show up as unavailable! I dont understand why. 

This is my configuration:
`virtual:
light:
  - platform: virtual
    name: "Ledshelf"
    initial_value: "on"
    support_brightness: true
    initial_brightness: 100
  - platform: virtual
    name: "Ledshelf hours"
    initial_value: "on"
    support_color: true
    initial_color: [0, 255, 0]
  - platform: virtual
    name: "Ledshelf minutes"
    initial_value: "on"
    support_color: true
    initial_color: [0, 255, 0]`

And this is what i see in the entity window:
![image](https://github.com/twrecked/hass-virtual/assets/65161300/ac547dfe-d973-4a7c-b46d-d2779879993f)

As you can see, the first light (that i created a few days prior) works perfectly fine, but the lights i added later are unavailable! Why is this the case?

with regards,
Daniël

**Comment by ildar170975** [comment]
Difficult to guess since the code is not properly formatted.
Place the code inside triple "`".
