### ISSUE TITLE
service virtual.set value from a other entity 

### ISSUE THREAD

**Issue by jove01** [twrecked/hass-virtual#69]
Is there a way with the service "virtual.se"t , to set the value from another entity to fill a virtual sensor? I need it in a automation.
I recieve allways the error
`[140324082617920] Error handling message: value should be a string for dictionary value @ data['value']. Got None (invalid_format)`
`websocket_api script: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['value']`
I didn't find any help here or with google search (I am a beginner).

**Comment by twrecked** [comment]
You should be able to do it with an automation but it requires the virtual entity to be a `sensor`. If you can paste the virtual configuration and the automation I can take a look.

**Comment by jove01** [comment]
Thankyou
I will try it with a normal Templates Sensor. But i Need some days, so i Close this issue.
