### ISSUE TITLE
0.8.x I just cant get it to work anymore

### ISSUE THREAD

**Issue by DVEntertainment** [twrecked/hass-virtual#86]
I've tried to update to 0.8.x. It was still working out of my configuration.yaml. When i tried to update to virtual.yaml my virtual objects just wouldnt come back! If i try to add new ones they wont come up either.
This is my setup: virtual.yaml in a folder called virtuals. (ive reinstalled the component, it didnt create this yaml out of its own).
I have this line in my configuration.yaml
```
homeassistant:
    packages: !include_dir_named virtuals 
```

And in the virtual.yaml i have this content, ive copied the example in hopes of creating some test-virtuals but that didnt work either.
```
virtual:
  version: 1
  devices:
    Living Room Sensor:
      - platform: binary_sensor
        name: Living Room Motion
        initial_value: "off"
        class: motion
    Back Door Sensor:
      - platform: binary_sensor
        name: Back Door
        initial_value: "off"
        class: door
```

Am i doing something wrong?

Thank you so much

**Comment by twrecked** [comment]
If you are on 0.8 you should use these docs: https://github.com/twrecked/hass-virtual/tree/version-0.8.x#readme

0.8 still uses the old mechanism where devices are defined in the appropriate `yaml` sections.

**Comment by DVEntertainment** [comment]
Ohh my bad, i didnt read your comment correctly.. Ive installed .9 and everything works as expected now.
